# Start AeroSpace at login
start-at-login = false

# Run Sketchybar
after-startup-command = ['exec-and-forget sketchybar']

# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
    inner.horizontal = 10
    inner.vertical =   10
    outer.left =       10
    outer.bottom =     10
    outer.top =        48
    outer.right =      10

[mode.main.binding]
    # Focus window
    alt-j =         'focus --boundaries-action wrap-around-the-workspace left'
    alt-k =         'focus --boundaries-action wrap-around-the-workspace down'
    alt-i =         'focus --boundaries-action wrap-around-the-workspace up'
    alt-l = 'focus --boundaries-action wrap-around-the-workspace right'

    # Move window
    alt-shift-j = 'move left'
    alt-shift-k = 'move down'
    alt-shift-i = 'move up'
    alt-shift-l = 'move right'

    # Layout like i3
    alt-h = 'split horizontal'
    alt-v = 'split vertical'
    alt-f = 'fullscreen'
    alt-s = 'layout v_accordion' # 'layout stacking' in i3
    alt-w = 'layout h_accordion' # 'layout tabbed' in i3
    alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3
    alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

    # Change workspace
    ctrl-q= 'workspace 1'
    ctrl-w = 'workspace 2'
    ctrl-e = 'workspace 3'
    ctrl-r = 'workspace 4'
    ctrl-t = 'workspace 5'
    ctrl-y = 'workspace 6'
    ctrl-u = 'workspace 7'
    ctrl-i = 'workspace 8'
    ctrl-o = 'workspace 9'
    ctrl-p = 'workspace 10'

    # Move window to workspace
    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'
    alt-shift-7 = 'move-node-to-workspace 7'
    alt-shift-8 = 'move-node-to-workspace 8'
    alt-shift-9 = 'move-node-to-workspace 9'
    alt-shift-0 = 'move-node-to-workspace 10'

    alt-shift-c = 'reload-config'
    alt-r = 'mode resize'

[mode.resize.binding]
    j = 'resize smart -50'
    l = 'resize smart +50'

    enter = 'mode main'
    esc = 'mode main'
